apiVersion: v1
kind: Secret
metadata:
  name: othello-secrets
  namespace: othello
type: Opaque
stringData:
  JWT_SIGNER_KEY: "a5ec3c15e4118e3bf5be7f45a02434dd577a9397a3896e0634b4512148f05aa7"
  POSTGRES_PASSWORD: "postgres"
  USER_DB_USERNAME: "user_service_acc"
  USER_DB_PASSWORD: "UserPassword@123"
  AI_DB_USERNAME: "ai_service_acc"
  AI_DB_PASSWORD: "AiPassword@123"
  PVP_DB_USERNAME: "pvp_service_acc"
  PVP_DB_PASSWORD: "PvpPassword@123"
  LEADER_DB_USERNAME: "leaderboard_service_acc"
  LEADER_DB_PASSWORD: "LeaderPassword@123"
