apiVersion: v1
kind: Secret
metadata:
  name: othello-secrets
  namespace: othello
type: Opaque
stringData:
  JWT_SIGNER_KEY: "${JWT_SIGNER_KEY}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  USER_DB_USERNAME: "${USER_DB_USERNAME}"
  USER_DB_PASSWORD: "${USER_DB_PASSWORD}"
  AI_DB_USERNAME: "${AI_DB_USERNAME}"
  AI_DB_PASSWORD: "${AI_DB_PASSWORD}"
  PVP_DB_USERNAME: "${PVP_DB_USERNAME}"
  PVP_DB_PASSWORD: "${PVP_DB_PASSWORD}"
  LEADER_DB_USERNAME: "${LEADER_DB_USERNAME}"
  LEADER_DB_PASSWORD: "${LEADER_DB_PASSWORD}"
