server:
  port: 8082

spring:
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties]
  application:
    name: ${AI_MODEL_SERVICE_NAME:ai-model-service}
  datasource:
    url: ${DB_URL_AI_MODEL}
    username: ${DB_USERNAME_AI_MODEL}
    password: ${DB_PASSWORD_AI_MODEL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  signerKey: ${JWT_SIGNER_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}